language: node_js
arch:
 - amd64
 - ppc64le

node_js:
  - '6'
  - '5'
  - '4'
  - '0.12'
  - '0.10'

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

after_script:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls'
